=begin
#Vantage

#Vantage API

OpenAPI spec version: 1.0.0
Contact: support@vantage.sh
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.21

=end

require 'spec_helper'
require 'json'

# Unit tests for Vantage::CostsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CostsApi' do
  before do
    # run before each test
    @instance = Vantage::CostsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CostsApi' do
    it 'should create an instance of CostsApi' do
      expect(@instance).to be_instance_of(Vantage::CostsApi)
    end
  end

  # unit tests for get_costs
  # Return available Costs for the specified Cost Report and optional time period. If no time period is specified it will return all available costs for the report.
  # @param report_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Query costs by the first date you would like to filter from. ISO 8601 Formatted - 2021-07-15 or 2021-07-15T19:20:48+00:00.
  # @option opts [String] :end_date Query costs by the last date you would like to filter to. ISO 8601 Formatted - 2021-07-15 or 2021-07-15T19:20:48+00:00.
  # @option opts [Integer] :page The page of results to return.
  # @option opts [Integer] :limit The amount of results to return. The maximum is 1000
  # @return [Costs]
  describe 'get_costs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_report
  # Return a Cost Report.
  # @param report_id 
  # @param [Hash] opts the optional parameters
  # @return [Report]
  describe 'get_report test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_reports
  # Return all Cost Reports.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to return.
  # @option opts [Integer] :limit The amount of results to return. The maximum is 1000
  # @return [Reports]
  describe 'get_reports test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
