=begin
#Vantage

#Vantage API

OpenAPI spec version: 1.0.0
Contact: support@vantage.sh
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.21

=end

require 'spec_helper'
require 'json'

# Unit tests for Vantage::PingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PingApi' do
  before do
    # run before each test
    @instance = Vantage::PingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PingApi' do
    it 'should create an instance of PingApi' do
      expect(@instance).to be_instance_of(Vantage::PingApi)
    end
  end

  # unit tests for ping
  # This is a health check endpoint that can be used to determine Vantage API healthiness. It will return 200 if everything is running smoothly.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
