=begin
#Vantage

#Vantage API

OpenAPI spec version: 1.0.0
Contact: support@vantage.sh
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.21

=end

# Common files
require 'vantage-client/api_client'
require 'vantage-client/api_error'
require 'vantage-client/version'
require 'vantage-client/configuration'

# Models
require 'vantage-client/models/cost'
require 'vantage-client/models/costs'
require 'vantage-client/models/price'
require 'vantage-client/models/prices'
require 'vantage-client/models/product'
require 'vantage-client/models/products'
require 'vantage-client/models/provider'
require 'vantage-client/models/providers'
require 'vantage-client/models/report'
require 'vantage-client/models/reports'
require 'vantage-client/models/service'
require 'vantage-client/models/services'

# APIs
require 'vantage-client/api/costs_api'
require 'vantage-client/api/ping_api'
require 'vantage-client/api/prices_api'

module Vantage
  class << self
    # Customize default settings for the SDK using block.
    #   Vantage.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
